package io.quarkus.bot.it;

import static io.quarkiverse.githubapp.testing.GitHubAppTesting.given;
import static io.quarkus.bot.it.MockHelper.mockUser;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.util.Set;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.kohsuke.github.GHEvent;
import org.kohsuke.github.GHOrganization;
import org.kohsuke.github.GHTeam;
import org.kohsuke.github.GHUser;
import org.mockito.junit.jupiter.MockitoExtension;

import io.quarkiverse.githubapp.testing.GitHubAppTest;
import io.quarkiverse.githubapp.testing.dsl.GitHubMockSetupContext;
import io.quarkus.cache.CacheInvalidateAll;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
@GitHubAppTest
@ExtendWith(MockitoExtension.class)
public class CheckPullRequestSimilarGitHubHandleTest {

    private static final String CONFIG = """
            features: [ CHECK_SIMILAR_GITHUB_HANDLES ]
            similarGitHubHandleCheck:
              org: quarkusio
              teams: [quarkus-admin, quarkus-push]
            """;

    private static final String EXPECTED_COMMENT = """
            > [!WARNING]
            > We noticed that your GitHub handle is very similar to that of a team member.
            >
            > To avoid any confusion, we wanted to flag this so that reviewers can double-check.
            > No action is needed on your part. Thank you for your understanding!

            /cc @gsmet

            <sub>This message is automatically generated by a bot.</sub>
            <!-- Quarkus-Bot-Similar-GitHub-Handle -->""";

    @CacheInvalidateAll(cacheName = "team-members-cache")
    void setupTeamMocks(GitHubMockSetupContext mocks) throws Exception {
        GHOrganization org = mock(GHOrganization.class);
        when(mocks.installationClient(13173124L).getOrganization("quarkusio")).thenReturn(org);

        GHTeam adminTeam = mock(GHTeam.class);
        GHTeam pushTeam = mock(GHTeam.class);
        when(org.getTeamBySlug("quarkus-admin")).thenReturn(adminTeam);
        when(org.getTeamBySlug("quarkus-push")).thenReturn(pushTeam);

        GHUser gsmet = mockUser("gsmet");
        GHUser maxandersen = mockUser("maxandersen");
        when(adminTeam.getMembers()).thenReturn(Set.of(gsmet, maxandersen));
        when(pushTeam.getMembers()).thenReturn(Set.of(gsmet));
    }

    @Test
    void similarHandleShouldPostComment() throws Exception {
        given().github(mocks -> {
            mocks.configFile("quarkus-github-bot.yml").fromString(CONFIG);
            setupTeamMocks(mocks);
        })
                .when().payloadFromClasspath("/pullrequest-opened-similar-github-handle.json")
                .event(GHEvent.PULL_REQUEST)
                .then().github(mocks -> {
                    verify(mocks.pullRequest(527350930)).comment(EXPECTED_COMMENT);
                });
    }

    @Test
    void exactTeamMemberHandleShouldNotPostComment() throws Exception {
        given().github(mocks -> {
            mocks.configFile("quarkus-github-bot.yml").fromString(CONFIG);
            setupTeamMocks(mocks);
        })
                .when().payloadFromClasspath("/pullrequest-opened-team-member.json")
                .event(GHEvent.PULL_REQUEST)
                .then().github(mocks -> {
                    verifyNoMoreInteractions(mocks.ghObjects());
                });
    }

    @Test
    void unrelatedHandleShouldNotPostComment() throws Exception {
        given().github(mocks -> {
            mocks.configFile("quarkus-github-bot.yml").fromString(CONFIG);
            setupTeamMocks(mocks);
        })
                // yrodiere is unrelated to any team member
                .when().payloadFromClasspath("/pullrequest-opened-title-ends-with-dot.json")
                .event(GHEvent.PULL_REQUEST)
                .then().github(mocks -> {
                    verifyNoMoreInteractions(mocks.ghObjects());
                });
    }

    @Test
    void featureDisabledShouldNotPostComment() throws Exception {
        given().github(mocks -> {
            mocks.configFile("quarkus-github-bot.yml")
                    .fromString("features: [ CHECK_EDITORIAL_RULES ]\n");
        })
                .when().payloadFromClasspath("/pullrequest-opened-similar-github-handle.json")
                .event(GHEvent.PULL_REQUEST)
                .then().github(mocks -> {
                    verifyNoMoreInteractions(mocks.ghObjects());
                });
    }
}
