package io.quarkus.bot.util;

public class Strings {

    public static boolean isNotBlank(String string) {
        return string != null && !string.trim().isEmpty();
    }

    public static boolean isBlank(String string) {
        return string == null || string.trim().isEmpty();
    }

    public static String commentByBot(String originalComment) {
        StringBuilder sb = new StringBuilder(originalComment);
        if (!originalComment.endsWith("\n")) {
            sb.append("\n");
        }
        sb.append("\n> This message is automatically generated by a bot.");
        return sb.toString();
    }

    private Strings() {
    }
}
