package io.quarkus.bot.workflow;

import static org.assertj.core.api.Assertions.assertThat;

import javax.inject.Inject;

import org.junit.jupiter.api.Test;

import io.quarkus.bot.buildreporter.StackTraceShortener;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class StackTraceShortenerTest {

    @Inject
    StackTraceShortener stackTraceShortener;

    @Test
    public void testAbbreviate() {
        assertThat(stackTraceShortener.shorten(
                "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details\n"
                        + "    at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:73)\n"
                        + "    at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:116)\n"
                        + "    at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:129)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:126)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)\n"
                        + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)\n"
                        + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)\n"
                        + "    ... 34 more",
                1500)).isEqualTo(
                        "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details\n"
                                + "    at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:73)\n"
                                + "    at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:116)\n"
                                + "    at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:129)\n"
                                + "    at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:126)\n"
                                + "    at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)\n"
                                + "    at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)\n"
                                + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)\n"
                                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                                + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)\n"
                                + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)\n"
                                + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)\n"
                                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)\n"
                                + "    ... 34 more");

        assertThat(stackTraceShortener.shorten("java.lang.AssertionError: \n"
                + "1 expectation failed.\n"
                + "Response body doesn't match expectation.\n"
                + "Expected: is \"[decoded][encoded]initial data\"\n"
                + "  Actual: <!doctype html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <title>Internal Server Error - Error handling 7011d4a4-d7ed-4c33-8d6a-881a5c63b8c4-1, javax.enterprise.context.ContextNotActiveException: </title>\n"
                + "    <meta charset=\"utf-8\">\n"
                + "    <style>\n"
                + "html, body {\n"
                + "    margin: 0;\n"
                + "    padding: 0;\n"
                + "    font-family: 'Open Sans', Helvetica, Arial, sans-serif;\n"
                + "    font-size: 100%;\n"
                + "    font-weight: 100;\n"
                + "    line-height: 1.4;\n"
                + "}\n"
                + "\n"
                + "html {\n"
                + "    overflow-y: scroll;\n"
                + "}\n"
                + "\n"
                + "body {\n"
                + "    background: #f9f9f9;\n"
                + "}\n"
                + ".container {\n"
                + "    width: 80%;\n"
                + "    margin: 0 auto;\n"
                + "}\n"
                + ".content {\n"
                + "    padding: 1em 0 1em 0;\n"
                + "}\n"
                + "\n"
                + "header, .component-name {\n"
                + "    background-color: #ad1c1c;\n"
                + "}\n"
                + "\n"
                + "ul {\n"
                + "    line-height: 1.5rem;\n"
                + "    margin: 0.25em 0 0.25em 0;\n"
                + "}\n"
                + "\n"
                + ".exception-message {\n"
                + "    background: #be2828;\n"
                + "}\n"
                + "\n"
                + "h1, h2 {\n"
                + "    margin: 0;\n"
                + "    padding: 0;\n"
                + "}\n"
                + "\n"
                + "h1 {\n"
                + "    font-size: 2rem;\n"
                + "    color: #fff;\n"
                + "    line-height: 3.75rem;\n"
                + "    font-weight: 700;\n"
                + "    padding: 0.4rem 0rem 0.4rem 0rem;\n"
                + "}\n"
                + "\n"
                + "h2 {\n"
                + "    font-size: 1.2rem;\n"
                + "    color: rgba(255, 255, 255, 0.85);\n"
                + "    line-height: 2.5rem;\n"
                + "    font-weight: 400;\n"
                + "    padding: 0.4rem 0rem 0.4rem 0rem;\n"
                + "}\n"
                + "\n"
                + ".intro {    font-size: 1.2rem;\n"
                + "    font-weight: 400;\n"
                + "    margin: 0.25em 0 1em 0;\n"
                + "}\n"
                + "h3 {\n"
                + "    font-size: 1.2rem;\n"
                + "    line-height: 2.5rem;\n"
                + "    font-weight: 400;\n"
                + "    color: #555;\n"
                + "    margin: 0.25em 0 0.25em 0;\n"
                + "}\n"
                + "\n"
                + ".trace, .resources {\n"
                + "    background: #fff;\n"
                + "    padding: 15px;\n"
                + "    margin: 15px auto;\n"
                + "    border: 1px solid #ececec;\n"
                + "}\n"
                + ".trace {\n"
                + "    overflow-y: scroll;\n"
                + "}\n"
                + ".hidden {\n"
                + "   display: none;\n"
                + "}\n"
                + "\n"
                + "pre {\n"
                + "    white-space: pre;\n"
                + "    font-family: Consolas, Monaco, Menlo, \"Ubuntu Mono\", \"Liberation Mono\", monospace;\n"
                + "    font-size: 12px;\n"
                + "    line-height: 1.5;\n"
                + "    color: #555;\n"
                + "}\n"
                + "</style>\n"
                + "<script>\n"
                + "    function toggleStackTraceOrder() {\n"
                + "        var stElement = document.getElementById('stacktrace');\n"
                + "        var current = stElement.getAttribute('data-current-setting');\n"
                + "        if (current == 'original-stacktrace') {\n"
                + "            var reverseOrder = document.getElementById('reversed-stacktrace');\n"
                + "            stElement.innerHTML = reverseOrder.innerHTML;\n"
                + "            stElement.setAttribute('data-current-setting', 'reversed-stacktrace');\n"
                + "        } else {\n"
                + "            var originalOrder = document.getElementById('original-stacktrace');\n"
                + "            stElement.innerHTML = originalOrder.innerHTML;\n"
                + "            stElement.setAttribute('data-current-setting', 'original-stacktrace');\n"
                + "        }\n"
                + "        return;\n"
                + "    }\n"
                + "    function showDefaultStackTraceOrder() {\n"
                + "        var reverseOrder = document.getElementById('reversed-stacktrace');\n"
                + "        var stElement = document.getElementById('stacktrace');\n"
                + "       if (reverseOrder == null || stElement == null) {\n"
                + "           return;\n"
                + "       }\n"
                + "        // default to reverse ordered stacktrace\n"
                + "        stElement.innerHTML = reverseOrder.innerHTML;\n"
                + "        stElement.setAttribute('data-current-setting', 'reversed-stacktrace');\n"
                + "        return;\n"
                + "    }\n"
                + "</script>\n"
                + "</head>\n"
                + "<body  onload=\"showDefaultStackTraceOrder()\">\n"
                + "<header>\n"
                + "    <h1 class=\"container\">Internal Server Error</h1>\n"
                + "    <div class=\"exception-message\">\n"
                + "        <h2 class=\"container\">Error handling 7011d4a4-d7ed-4c33-8d6a-881a5c63b8c4-1, javax.enterprise.context.ContextNotActiveException: </h2>\n"
                + "    </div>\n"
                + "</header>\n"
                + "<div class=\"container content\">\n"
                + "    <div id=\"original-stacktrace\" class=\"trace hidden\">\n"
                + "<p><em><a href=\"\" onClick=\"toggleStackTraceOrder(); return false;\">Click Here</a> to see the stacktrace in reversed  order (root-cause first)</em></p>        <pre>javax.enterprise.context.ContextNotActiveException\n"
                + "    at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)\n"
                + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:60)\n"
                + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.request(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:354)\n"
                + "    at io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric.getRequestMetric(HttpRequestMetric.java:75)\n"
                + "    at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderUndertowServletFilter.doFilter(VertxMeterBinderUndertowServletFilter.java:31)\n"
                + "    at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)\n"
                + "    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n"
                + "    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n"
                + "    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n"
                + "    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)\n"
                + "    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)\n"
                + "    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)\n"
                + "    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)\n"
                + "    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)\n"
                + "    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)\n"
                + "    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)\n"
                + "    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)\n"
                + "    at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)\n"
                + "    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)\n"
                + "    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)\n"
                + "    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)\n"
                + "    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)\n"
                + "    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)\n"
                + "    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:587)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)\n"
                + "    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)\n"
                + "    at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:413)\n"
                + "    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n"
                + "    at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n"
                + "    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)\n"
                + "    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)\n"
                + "    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n"
                + "    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n"
                + "    at java.lang.Thread.run(Thread.java:748)\n"
                + "    at org.jboss.threads.JBossThread.run(JBossThread.java:501)</pre>\n"
                + "    </div>\n"
                + "    <div id=\"reversed-stacktrace\" class=\"trace hidden\">\n"
                + "<p><em>The stacktrace below has been reversed to show the root cause first. <a href=\"\" onClick=\"toggleStackTraceOrder(); return false;\">Click Here</a> to see the original stacktrace</em></p>        <pre>javax.enterprise.context.ContextNotActiveException\n"
                + "    at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)\n"
                + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:60)\n"
                + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.request(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:354)\n"
                + "    at io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric.getRequestMetric(HttpRequestMetric.java:75)\n"
                + "    at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderUndertowServletFilter.doFilter(VertxMeterBinderUndertowServletFilter.java:31)\n"
                + "    at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)\n"
                + "    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n"
                + "    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n"
                + "    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n"
                + "    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)\n"
                + "    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)\n"
                + "    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)\n"
                + "    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)\n"
                + "    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)\n"
                + "    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)\n"
                + "    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)\n"
                + "    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)\n"
                + "    at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)\n"
                + "    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)\n"
                + "    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)\n"
                + "    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)\n"
                + "    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)\n"
                + "    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)\n"
                + "    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:587)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)\n"
                + "    at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)\n"
                + "    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)\n"
                + "    at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)\n"
                + "    at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:413)\n"
                + "    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n"
                + "    at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n"
                + "    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)\n"
                + "    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)\n"
                + "    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n"
                + "    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n"
                + "    at java.lang.Thread.run(Thread.java:748)\n"
                + "    at org.jboss.threads.JBossThread.run(JBossThread.java:501)</pre>\n"
                + "    </div>\n"
                + "<div id=\"stacktrace\"></div></div></body>\n"
                + "</html>", 1500)).isEqualTo("java.lang.AssertionError: \n"
                        + "1 expectation failed.\n"
                        + "Response body doesn't match expectation.\n"
                        + "Expected: is \"[decoded][encoded]initial data\"\n"
                        + "  Actual: An Internal Server Error with stack trace:\n"
                        + "javax.enterprise.context.ContextNotActiveException\n"
                        + "    at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)\n"
                        + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:60)\n"
                        + "    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.request(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:354)\n"
                        + "    at io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric.getRequestMetric(HttpRequestMetric.java:75)\n"
                        + "    at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderUndertowServletFilter.doFilter(VertxMeterBinderUndertowServletFilter.java:31)\n"
                        + "    at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)\n"
                        + "    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n"
                        + "    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n"
                        + "    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n"
                        + "    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(S...");

        assertThat(stackTraceShortener.shorten("java.net.SocketTimeoutException: Read timed out\n"
                + "    at java.base/java.net.SocketInputStream.socketRead0(Native Method)\n"
                + "    at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)\n"
                + "    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)\n"
                + "    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)\n"
                + "    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)\n"
                + "    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)\n"
                + "    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)\n"
                + "    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)\n"
                + "    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)\n"
                + "    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)\n"
                + "    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)\n"
                + "    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)\n"
                + "    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207)\n"
                + "    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)\n"
                + "    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)\n"
                + "    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)\n"
                + "    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:481)\n"
                + "    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)\n"
                + "    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n"
                + "    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)\n"
                + "    at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2055)\n"
                + "    at io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:495)\n"
                + "    at io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:452)\n"
                + "    at io.restassured.internal.http.HTTPBuilder$request$2.call(Unknown Source)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1451)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1200)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)\n"
                + "    at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)\n"
                + "    at io.restassured.filter.Filter$filter$0.call(Unknown Source)\n"
                + "    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)\n"
                + "    at io.restassured.filter.Filter$filter.call(Unknown Source)\n"
                + "    at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)\n"
                + "    at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)\n"
                + "    at io.restassured.filter.Filter$filter.call(Unknown Source)\n"
                + "    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)\n"
                + "    at io.restassured.filter.Filter$filter$0.call(Unknown Source)\n"
                + "    at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)\n"
                + "    at io.restassured.filter.FilterContext$next.call(Unknown Source)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1655)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1661)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:171)\n"
                + "    at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)\n"
                + "    at io.quarkus.it.kafka.SaslKafkaConsumerTest.testReception(SaslKafkaConsumerTest.java:48)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                + "    at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:939)\n"
                + "    at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:845)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)\n"
                + "    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)\n"
                + "    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)\n"
                + "    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)\n"
                + "    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)\n"
                + "    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)\n"
                + "    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)\n"
                + "    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)\n"
                + "    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)\n"
                + "    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)\n"
                + "    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)\n"
                + "    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)\n"
                + "    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)\n"
                + "    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)\n"
                + "    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n"
                + "    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)\n"
                + "    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)\n"
                + "    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n"
                + "    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)\n"
                + "    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)\n"
                + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)\n"
                + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)\n"
                + "    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)\n"
                + "    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)\n"
                + "    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)\n"
                + "    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)\n"
                + "    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)\n"
                + "    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)\n"
                + "    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)\n"
                + "    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)\n"
                + "    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)\n"
                + "    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)\n"
                + "    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)\n"
                + "    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)\n"
                + "    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)\n"
                + "    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)\n"
                + "    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\n"
                + "    at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)\n"
                + "    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)",
                65000)).isEqualTo("java.net.SocketTimeoutException: Read timed out\n"
                        + "    at java.base/java.net.SocketInputStream.socketRead0(Native Method)\n"
                        + "    at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)\n"
                        + "    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)\n"
                        + "    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)\n"
                        + "    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)\n"
                        + "    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)\n"
                        + "    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)\n"
                        + "    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)\n"
                        + "    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)\n"
                        + "    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)\n"
                        + "    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)\n"
                        + "    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)\n"
                        + "    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207)\n"
                        + "    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)\n"
                        + "    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)\n"
                        + "    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)\n"
                        + "    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:481)\n"
                        + "    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)\n"
                        + "    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n"
                        + "    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)\n"
                        + "    at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2055)\n"
                        + "    at io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:495)\n"
                        + "    at io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:452)\n"
                        + "    at io.restassured.internal.http.HTTPBuilder$request$2.call(Unknown Source)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1451)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                        + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                        + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                        + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                        + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                        + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1200)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                        + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                        + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                        + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                        + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                        + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)\n"
                        + "    at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)\n"
                        + "    at io.restassured.filter.Filter$filter$0.call(Unknown Source)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)\n"
                        + "    at io.restassured.filter.Filter$filter.call(Unknown Source)\n"
                        + "    at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)\n"
                        + "    at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)\n"
                        + "    at io.restassured.filter.Filter$filter.call(Unknown Source)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)\n"
                        + "    at io.restassured.filter.Filter$filter$0.call(Unknown Source)\n"
                        + "    at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)\n"
                        + "    at io.restassured.filter.FilterContext$next.call(Unknown Source)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1655)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                        + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                        + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                        + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                        + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                        + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1661)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                        + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                        + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)\n"
                        + "    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)\n"
                        + "    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)\n"
                        + "    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)\n"
                        + "    at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)\n"
                        + "    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:171)\n"
                        + "    at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)\n"
                        + "    at io.quarkus.it.kafka.SaslKafkaConsumerTest.testReception(SaslKafkaConsumerTest.java:48)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n"
                        + "    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n"
                        + "    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n"
                        + "    at java.base/java.lang.reflect.Method.invoke(Method.java:566)");
    }

    @Test
    public void testFirstLines() {
        assertThat(stackTraceShortener.shorten(
                "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details\n"
                        + "    at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:73)\n"
                        + "    at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:116)\n"
                        + "    at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:129)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:126)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)\n"
                        + "    at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)\n"
                        + "    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)\n"
                        + "    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)\n"
                        + "    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)\n"
                        + "    ... 34 more",
                10000, 3)).isEqualTo(
                        "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details\n"
                                + "    at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:73)\n"
                                + "    at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:116)");

        assertThat(stackTraceShortener.shorten(
                "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details",
                10000, 3)).isEqualTo(
                        "java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details");
    }
}
